---
build_from:
  aarch64: 'ghcr.io/home-assistant/aarch64-base:3.21'
  armhf: 'ghcr.io/home-assistant/armhf-base:3.21'
  armv7: 'ghcr.io/home-assistant/armv7-base:3.21'
  amd64: 'ghcr.io/home-assistant/amd64-base:3.21'
  i386: 'ghcr.io/home-assistant/i386-base:3.21'
labels:
  org.opencontainers.image.title: 'Home Assistant Add-on: GoDaddy Dynamic DNS Updater'
  org.opencontainers.image.description: "GoDaddy Dynamic DNS updating service with Let's Encrypt support."
  org.opencontainers.image.source: 'https://github.com/mreditor97/homeassistant-addons'
  org.opencontainers.image.licenses: 'MIT'
