---
build_from:
  aarch64: 'ghcr.io/hassio-addons/base:14.0.0'
  armhf: 'ghcr.io/hassio-addons/base:14.0.0'
  armv7: 'ghcr.io/hassio-addons/base:14.0.0'
  amd64: 'ghcr.io/hassio-addons/base:14.0.0'
  i386: 'ghcr.io/hassio-addons/base:14.0.0'
labels:
  org.opencontainers.image.title: 'Home Assistant Add-on: GoDaddy DNS Updater'
  org.opencontainers.image.description: "GoDaddy DNS updating service with Let's Encrypt support."
  org.opencontainers.image.source: 'https://github.com/mreditor97/homeassistant-addons'
  org.opencontainers.image.licenses: 'MIT'
