---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ['CI']
    branches: [master]
    types:
      - completed

jobs:
  workflows:
    name: Add-on Deploy
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@main
    with:
      repository: 'homeassistant-addons'
      repository_beta: 'homeassistant-addons-beta'
      repository_edge: 'homeassistant-addons-edge'
    secrets:
      CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
